/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.unipar.pcbuild;

import static br.com.unipar.pcbuild.CadastroPc.pilhaPc;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Pessinera
 */
public class ListPc extends javax.swing.JFrame {

    String[] columnNames = {"Pecas", "Valor Total"};
    Object[][] data;
    DefaultTableModel model = new DefaultTableModel(data, columnNames) {
        //não permitir editar a celula da table;
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    ;

    };
    public ListPc() {
        initComponents();
        preencheData();
        setVisible(true);
    }

    private void preencheData() {

        model = (DefaultTableModel) jTable1.getModel();
        ((DefaultTableModel) jTable1.getModel()).setRowCount(0);

        while (!pilhaPc.isEmpty()) {
            for (int i = 0; i < CadastroPc.pilhaPc.top().getPecas().size(); CadastroPc.pilhaPc.pop()) {

                model.addRow(new Object[]{
                    CadastroPc.pilhaPc.top().getPecas().get(i).getNome(),
                    CadastroPc.pilhaPc.top().getVlTotal(),});
            }

        }
        //setar tamanho da coluna 2 como 20
        TableColumn col = jTable1.getColumnModel().getColumn(1);
        int width = 20;

        col.setPreferredWidth(width);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
